### ISSUE TITLE
Remove dashes/spaces in BackpagePhone table

### ISSUE THREAD

**Issue by bmenn** [anidata/ht-etl#3]
Per request from anidata/ht-archive#10, phone numbers should be stored without dashes, spaces, or other special symbols.

Tasks to do:
- [ ] Create Luigi Task to strip special characters

**Comment by hank-bond** [comment]
I dont think we need a task for this since we can do this in sql and it only takes a second to run.

`UPDATE backpagephone SET number = regexp_replace(number, '[-\n]', '', 'g');`

This fixes up 100% of the records.

**Comment by dlrobertson** [comment]
Resolved by #12
