### ISSUE TITLE
Create Luigi Task to extract phone numbers

### ISSUE THREAD

**Issue by bmenn** [anidata/ht-etl#4]
From the requirements of #1, we need to be able to scrape out phone numbers of all manner from raw HTML. Would also suggest creating a `PhoneNumber` table with an auto increment ID, so phone number could be tracked across multiple sites.

Examples of phone number formats to handle (not exhaustive):
* `123-123-1234`
* `(123) 123-1234`
* `one two-3.123 dash one2three4`
* `one two three - one two three - one two three four`

**Comment by bmenn** [comment]
@baronvonbadguy 

Do you have any updates or need help on this issue?

**Comment by hank-bond** [comment]
Oh mate I totally forgot I had this assigned.  I've had some friends roll through this weekend so my schedule was a bit more hectic than I anticipated. I'll take a look into this tonight and see if I can get a PR up.

**Comment by hank-bond** [comment]
After meeting with @danlrobertson it appears we will need a common "pull records from raw table" task that we can use to feed both this task and also #5 with

**Comment by bmenn** [comment]
@baronvonbadguy @danlrobertson 

Anything I can help here?

**Comment by hank-bond** [comment]
I can make a ticket/branch for that task, and then base the branch for this ticket off that.

**Comment by gte620v** [comment]
Feel free to give it a shot.  I am backlogged with other work.

**Comment by dlrobertson** [comment]
Resolved by #12
