### ISSUE TITLE
Create Luigi Task to parse emails

### ISSUE THREAD

**Issue by bmenn** [anidata/ht-etl#5]
From the requirements of #1, we need to be able to scrape out emails of all manner from raw HTML. Would also suggest creating a EmailAddress table with an auto increment ID, so email could be tracked across multiple sites.

Examples of email address formats to handle (not exhaustive):

* `some.one@somewhere.com`
* `some.one at somewhere.com`
* `some dot one @ some where .com`

**Comment by bmenn** [comment]
@danlrobertson 

Do you have any updates or need help on this issue?

**Comment by lahoffm** [comment]
I mostly solved this (see pull request) but still needs improved regular expressions and parsing multiple emails from a posting instead of just the first one. Could be good mini-project for people newer to programming.

**Comment by dlrobertson** [comment]
Solved between #6 and #11
